; Rendering


[Antialiasing]
bUse4XAntialiasing = true


; Windows Information
[Position]
iWindowPosX = 514
iWindowPosY = 264


[Size]
iWindowWidth = 800
iWindowHeight = 561


[TitleBar]
bDisplay = true


; Input control
[Mouse]
bDisableMousePointer = true
bShowMousePointer = false
bUseMousePointerForMenu = true
bUseMousePointerForGameplay = true


; Frame Rate Information
[FrameRate]
FPS = 60
frameTime = 0.0166666666666667


; 2D Game Settings
[NumTiles]
NUM_TILES_XAXIS = 32
NUM_TILES_YAXIS = 24


[TileSize]
TILE_WIDTH = 0.062500
TILE_HEIGHT = 0.083333


; Shader files
[Shader]
Shader2D.vs = Shader//Shader2D.vs
Shader2D.fs = Shader//Shader2D.fs
Shader2D_Colour.vs = Shader//Shader2D_Colour.vs
Shader2D_Colour.fs = Shader//Shader2D_Colour.fs
Shader3D.vs = Shader//Shader3D.vs
Shader3D.fs = Shader//Shader3D.fs
Shader3D_Line.vs = Shader//Shader3D_LineShader.vs
Shader3D_Line.fs = Shader//Shader3D_LineShader.fs
Shader3D_SkyBox.vs = Shader//Shader3D_SkyBox.vs
Shader3D_SkyBox.fs = Shader//Shader3D_SkyBox.fs
Shader3D_NoColour.vs = Shader//Shader3D_NoColour.vs
Shader3D_NoColour.fs = Shader//Shader3D_NoColour.fs
Shader3D_Model.vs = Shader//Shader3D_Model.vs
Shader3D_Model.fs = Shader//Shader3D_Model.fs
Shader3D_RenderToTexture.vs = Shader//Shader3D_RenderToTexture.vs
Shader3D_RenderToTexture.fs = Shader//Shader3D_RenderToTexture.fs
Shader3D_Instancing.vs = Shader//Shader3D_Instancing.vs
Shader3D_Instancing.fs = Shader//Shader3D_Instancing.fs
Shader3D_Terrain.vs = Shader//Shader3D_Terrain.vs
Shader3D_Terrain.fs = Shader//Shader3D_Terrain.fs
Shader3D_Grass.vs = Shader//Shader3D_Grass.vs
Shader3D_Grass.fs = Shader//Shader3D_Grass.fs
Shader3D_Grass.gs = Shader//Shader3D_Grass.gs
Shader3D_Lights.vs = Shader//Shader3D_Lights.vs
Shader3D_Lights.fs = Shader//Shader3D_Lights.fs
